/**
 * @file products_data.ts
 * @description Datos mock para productos - VERSIÓN CORREGIDA
 */

import { type Product } from '@/types/product';

// ============================================================================
// PRODUCTOS DE EJEMPLO
// ============================================================================

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'prod-001',
    producerId: 'user-123',
    name: 'Queso Curado Artesanal 12 meses',
    slug: 'queso-curado-artesanal-12-meses',
    shortDescription: 'Queso de oveja curado durante 12 meses en cueva natural',
    fullDescription: 'Elaborado con leche cruda de oveja de nuestra propia ganadería en la Sierra de Grazalema. La leche se cuaja con cuajo natural de cordero y se prensa manualmente en moldes tradicionales de esparto. La maduración se realiza durante 12 meses en cuevas naturales, donde la humedad y temperatura constantes desarrollan su personalidad única.\n\nCaracterísticas:\n- Textura firme y ligeramente cristalizada\n- Sabor intenso y persistente con notas de frutos secos y hierbas de la sierra\n- Corteza natural lavada con aceite de oliva virgen extra\n\nReconocimientos:\n- Medalla de Oro en los World Cheese Awards 2024\n- Mejor Queso de España 2023 (Guía Gourmet)',
    categoryId: 'quesos',
    categoryName: 'Quesos',
    subcategoryId: 'curado',
    tags: ['artesano', 'ecológico', 'premiado', 'denominación origen', 'oveja', 'curado'],
    mainImage: {
      id: 'img-001',
      url: '/images/products/queso-curado.jpg',
      alt: 'Queso curado artesanal',
      caption: 'Queso curado 12 meses',
      isMain: true,
      sortOrder: 0,
    },
    gallery: [
      {
        id: 'img-002',
        url: '/images/products/queso-curado-2.jpg',
        alt: 'Queso curado - vista lateral',
        caption: 'Detalle de la corteza',
        isMain: false,
        sortOrder: 1,
      },
      {
        id: 'img-003',
        url: '/images/products/queso-curado-3.jpg',
        alt: 'Queso curado - corte',
        caption: 'Textura interior',
        isMain: false,
        sortOrder: 2,
      },
    ],
    basePrice: 24.50,
    comparePrice: 29.90,
    priceTiers: [
      { 
        id: 'tier1', 
        minQuantity: 2, 
        type: 'percentage', 
        value: 5, 
        label: '5% dto',
        savings: 2.45 
      },
      { 
        id: 'tier2', 
        minQuantity: 5, 
        type: 'percentage', 
        value: 10, 
        label: '10% dto',
        savings: 12.25 
      },
      { 
        id: 'tier3', 
        minQuantity: 10, 
        type: 'percentage', 
        value: 15, 
        label: '15% dto',
        savings: 36.75 
      },
    ],
    sku: 'QUESO-CURADO-012',
    barcode: '8434567890123',
    stock: 45,
    lowStockThreshold: 10,
    trackInventory: true,
    allowBackorders: false,
    weight: 1.2,
    weightUnit: 'kg',
    dimensions: { length: 18, width: 18, height: 10, unit: 'cm' },
    shippingClass: 'perishable',
    nutritionalInfo: {
      servingSize: '100g',
      servingSizeValue: 100,
      servingSizeUnit: 'g',
      calories: 420,
      protein: 28,
      totalFat: 34,
      saturatedFat: 22,
      transFat: 0.5,
      cholesterol: 85,
      sodium: 620,
      carbohydrates: 1.5,
      dietaryFiber: 0,
      sugars: 0.2,
      addedSugars: 0,
      vitamins: [
        {
          id: 'vit-a',
          name: 'Vitamina A',
          amount: 320,
          unit: 'µg',
          dailyValue: 40,
        },
        {
          id: 'vit-b12',
          name: 'Vitamina B12',
          amount: 1.5,
          unit: 'µg',
          dailyValue: 60,
        },
      ],
      allergens: ['Lácteos'],
      mayContain: ['Frutos de cáscara'],
      ingredients: [
        'Leche cruda de oveja (100% raza Manchega)',
        'Cuajo natural de cordero',
        'Sal marina',
        'Fermentos lácticos',
        'Cloruro cálcico'
      ],
      preparationInstructions: 'Servir a temperatura ambiente. Maridar con vinos tintos de la zona.',
      storageInstructions: 'Conservar en lugar fresco y seco. Una vez abierto, mantener refrigerado y consumir antes de 15 días.',
      isGlutenFree: true,
      isLactoseFree: false,
      isVegan: false,
      isVegetarian: true,
      isNutFree: false,
      isEggFree: true,
      isSoyFree: true,
    },
    certifications: [
      {
        id: 'cert-1',
        name: 'Denominación de Origen Protegida',
        issuingBody: 'Consejo Regulador D.O.',
        certificateNumber: 'DOP-2023-0456',
        issueDate: new Date('2023-01-15'),
        expiryDate: new Date('2025-12-31'),
        status: 'active',
        verified: true,
        category: 'origin',
      },
      {
        id: 'cert-2',
        name: 'Agricultura Ecológica UE',
        issuingBody: 'Comité Andaluz de Agricultura Ecológica',
        certificateNumber: 'ECO-AND-2023-0789',
        issueDate: new Date('2023-03-10'),
        expiryDate: new Date('2024-11-30'),
        status: 'active',
        verified: true,
        category: 'organic',
      },
    ],
    productionInfo: {
      story: '"Nuestros quesos son el reflejo de nuestra tierra. Cada pieza cuenta la historia de nuestras ovejas, que pastan en libertad en las laderas de la sierra, alimentándose de tomillo y romero." - María García, Maestra Quesera.',
      farmName: 'Quesería El Gazpacho',
      origin: 'Sierra de Grazalema, Cádiz',
      productionMethod: 'Artesanal tradicional',
      harvestDate: new Date('2024-02-15'),
      productionDate: new Date('2024-02-20'),
      expiryDate: new Date('2025-02-15'),
      batchNumber: 'LOTE-024-0224',
      sustainabilityInfo: 'Energía 100% renovable, reutilización de suero para alimentación animal, paneles solares, compostaje de residuos orgánicos.',
      animalWelfare: 'Cría en libertad, alimentación natural, pastoreo tradicional.',
      artisanProcess: 'Elaboración manual, prensado en moldes de esparto, maduración en cueva natural.',
      practices: ['renewable_energy', 'water_conservation', 'local_sourcing', 'biodiversity'],
      producerName: 'María García',
      media: [
        {
          id: 'media-1',
          type: 'image',
          url: '/images/production/queseria.jpg',
          preview: '/images/production/queseria.jpg',
          thumbnail: '/images/production/queseria-thumb.jpg',
          caption: 'Nuestra quesería en la sierra',
          sortOrder: 0,
          uploading: false,
          progress: 100,
        },
        {
          id: 'media-2',
          type: 'image',
          url: '/images/production/ovejas.jpg',
          preview: '/images/production/ovejas.jpg',
          thumbnail: '/images/production/ovejas-thumb.jpg',
          caption: 'Ovejas en pastoreo',
          sortOrder: 1,
          uploading: false,
          progress: 100,
        },
        {
          id: 'media-3',
          type: 'video',
          url: 'https://www.youtube.com/watch?v=example123',
          thumbnail: '/images/production/video-thumb.jpg',
          caption: 'Proceso de elaboración artesanal',
          sortOrder: 2,
          uploading: false,
          progress: 100,
        },
      ],
    },
    attributes: [
      { 
        id: 'attr-1', 
        name: 'Tipo de leche', 
        value: 'Oveja 100% Manchega', 
        type: 'text', 
        visible: true,
        description: 'Raza de oveja utilizada'
      },
      { 
        id: 'attr-2', 
        name: 'Tiempo de curación', 
        value: 12, 
        type: 'number', 
        unit: 'meses',
        visible: true,
        description: 'Período de maduración'
      },
      { 
        id: 'attr-3', 
        name: 'Maduración', 
        value: 'En cueva natural', 
        type: 'text', 
        visible: true,
        description: 'Método de maduración'
      },
      { 
        id: 'attr-4', 
        name: 'Textura', 
        value: 'Firme y cristalizada', 
        type: 'text', 
        visible: true,
        description: 'Consistencia del queso'
      },
      { 
        id: 'attr-5', 
        name: 'Intensidad', 
        value: 'Fuerte', 
        type: 'text', 
        visible: true,
        description: 'Nivel de sabor'
      },
    ],
    status: 'active',
    visibility: 'public',
    publishedAt: new Date('2024-01-15'),
    sales: 187,
    revenue: 4581.50,
    rating: 4.8,
    reviewCount: 42,
    views: 3452,
    conversion: 5.4,
    createdAt: new Date('2024-01-15T10:30:00Z'),
    updatedAt: new Date('2024-03-10T15:45:00Z'),
    lastOrderDate: new Date('2024-03-15T09:30:00Z'),
  },
  {
    id: 'prod-002',
    producerId: 'user-123',
    name: 'Aceite de Oliva Virgen Extra - Cosecha Temprana',
    slug: 'aceite-de-oliva-virgen-extra-cosecha-temprana',
    shortDescription: 'AOVE cosecha temprana, variedad picual',
    fullDescription: 'Aceite de oliva virgen extra de cosecha temprana, elaborado con aceitunas de la variedad picual. Recogidas en el momento óptimo de maduración y prensadas en frío en las 24 horas siguientes a la cosecha. De color verde intenso, aroma a hierba fresca y tomate, con un sabor frutado y ligeramente picante.',
    categoryId: 'aceites',
    categoryName: 'Aceites',
    subcategoryId: 'virgen-extra',
    tags: ['ecológico', 'cosecha temprana', 'picual', 'premiado'],
    mainImage: {
      id: 'img-004',
      url: '/images/products/aceite.jpg',
      alt: 'Aceite de oliva virgen extra',
      caption: 'AOVE Cosecha Temprana',
      isMain: true,
      sortOrder: 0,
    },
    gallery: [
      {
        id: 'img-005',
        url: '/images/products/aceite-2.jpg',
        alt: 'Botella de aceite',
        caption: 'Presentación en botella de vidrio',
        isMain: false,
        sortOrder: 1,
      },
    ],
    basePrice: 16.90,
    comparePrice: 19.90,
    priceTiers: [
      { 
        id: 'tier4', 
        minQuantity: 3, 
        type: 'percentage', 
        value: 10, 
        label: '10% dto',
        savings: 5.07 
      },
      { 
        id: 'tier5', 
        minQuantity: 6, 
        type: 'percentage', 
        value: 15, 
        label: '15% dto',
        savings: 15.21 
      },
    ],
    sku: 'ACEITE-001',
    barcode: '8434567890234',
    stock: 62,
    lowStockThreshold: 15,
    trackInventory: true,
    allowBackorders: false,
    weight: 0.5,
    weightUnit: 'kg',
    dimensions: { length: 7, width: 7, height: 25, unit: 'cm' },
    shippingClass: 'standard',
    nutritionalInfo: {
      servingSize: '100ml',
      servingSizeValue: 100,
      servingSizeUnit: 'ml',
      calories: 884,
      protein: 0,
      totalFat: 100,
      saturatedFat: 14,
      transFat: 0,
      cholesterol: 0,
      sodium: 2,
      carbohydrates: 0,
      dietaryFiber: 0,
      sugars: 0,
      addedSugars: 0,
      vitamins: [
        {
          id: 'vit-e',
          name: 'Vitamina E',
          amount: 14,
          unit: 'mg',
          dailyValue: 93,
        },
      ],
      allergens: [],
      mayContain: [],
      ingredients: ['Aceitunas de la variedad Picual (100%)'],
      preparationInstructions: 'Ideal para consumir en crudo, en ensaladas o sobre pan tostado.',
      storageInstructions: 'Conservar en lugar fresco y seco, protegido de la luz y el calor.',
      isGlutenFree: true,
      isLactoseFree: true,
      isVegan: true,
      isVegetarian: true,
      isNutFree: true,
      isEggFree: true,
      isSoyFree: true,
    },
    certifications: [
      {
        id: 'cert-3',
        name: 'Agricultura Ecológica UE',
        issuingBody: 'Comité Andaluz de Agricultura Ecológica',
        certificateNumber: 'ECO-AND-2023-0123',
        issueDate: new Date('2023-02-15'),
        expiryDate: new Date('2024-10-31'),
        status: 'active',
        verified: true,
        category: 'organic',
      },
      {
        id: 'cert-4',
        name: 'Producción Integrada',
        issuingBody: 'Junta de Andalucía',
        certificateNumber: 'PI-2023-0456',
        issueDate: new Date('2023-01-20'),
        expiryDate: new Date('2024-01-20'),
        status: 'expired',
        verified: true,
        category: 'quality',
      },
    ],
    productionInfo: {
      story: 'Nuestro aceite nace de olivos centenarios en la provincia de Jaén. La tradición familiar de más de 50 años nos ha enseñado a respetar los tiempos de la naturaleza y a extraer lo mejor de cada aceituna.',
      farmName: 'Olivar El Abuelo',
      origin: 'Jaén, Andalucía',
      productionMethod: 'Extracción en frío',
      harvestDate: new Date('2023-11-05'),
      productionDate: new Date('2023-11-10'),
      expiryDate: new Date('2025-11-10'),
      batchNumber: 'LOTE-023-1123',
      sustainabilityInfo: 'Agricultura ecológica certificada, paneles solares, reutilización de subproductos.',
      animalWelfare: 'No aplica (producto vegetal)',
      artisanProcess: 'Recolección manual y prensado en frío en menos de 24 horas.',
      practices: ['renewable_energy', 'local_sourcing', 'zero_waste'],
      producerName: 'Antonio Sánchez',
      media: [
        {
          id: 'media-4',
          type: 'image',
          url: '/images/production/olivar.jpg',
          preview: '/images/production/olivar.jpg',
          thumbnail: '/images/production/olivar-thumb.jpg',
          caption: 'Olivar centenario',
          sortOrder: 0,
          uploading: false,
          progress: 100,
        },
      ],
    },
    attributes: [
      { 
        id: 'attr-6', 
        name: 'Variedad', 
        value: 'Picual', 
        type: 'text', 
        visible: true,
        description: 'Variedad de aceituna'
      },
      { 
        id: 'attr-7', 
        name: 'Acidez', 
        value: 0.2, 
        type: 'number', 
        unit: '°',
        visible: true,
        description: 'Grado de acidez (máximo 0.8°)'
      },
      { 
        id: 'attr-8', 
        name: 'Cosecha', 
        value: 'Temprana', 
        type: 'text', 
        visible: true,
        description: 'Momento de la recolección'
      },
      { 
        id: 'attr-9', 
        name: 'Polifenoles', 
        value: 450, 
        type: 'number', 
        unit: 'mg/kg',
        visible: true,
        description: 'Contenido en polifenoles totales'
      },
    ],
    status: 'active',
    visibility: 'public',
    publishedAt: new Date('2023-11-15'),
    sales: 156,
    revenue: 2636.40,
    rating: 4.9,
    reviewCount: 38,
    views: 1890,
    conversion: 8.3,
    createdAt: new Date('2023-11-10T14:20:00Z'),
    updatedAt: new Date('2024-02-15T11:30:00Z'),
    lastOrderDate: new Date('2024-03-14T16:45:00Z'),
  },
  {
    id: 'prod-003',
    producerId: 'user-123',
    name: 'Miel de Romero Artesanal',
    slug: 'miel-de-romero-artesanal',
    shortDescription: 'Miel monofloral de romero de la Sierra de Alcaraz',
    fullDescription: 'Miel de romero pura, recolectada en las colmenas situadas en las montañas de la Sierra de Alcaraz. De color ámbar claro y aroma intenso a romero. Textura cremosa y cristalización natural. Perfecta para endulzar infusiones o para consumir directamente.',
    categoryId: 'mieles',
    categoryName: 'Mieles',
    subcategoryId: undefined,
    tags: ['artesano', 'monofloral', 'romero'],
    mainImage: {
      id: 'img-006',
      url: '/images/products/miel.jpg',
      alt: 'Miel de romero',
      caption: 'Miel de romero artesanal',
      isMain: true,
      sortOrder: 0,
    },
    gallery: [],
    basePrice: 8.95,
    comparePrice: undefined,
    priceTiers: [],
    sku: 'MIEL-001',
    barcode: undefined,
    stock: 23,
    lowStockThreshold: 6,
    trackInventory: true,
    allowBackorders: false,
    weight: 0.5,
    weightUnit: 'kg',
    dimensions: { length: 6, width: 6, height: 15, unit: 'cm' },
    shippingClass: 'standard',
    nutritionalInfo: {
      servingSize: '20g',
      servingSizeValue: 20,
      servingSizeUnit: 'g',
      calories: 64,
      protein: 0.1,
      totalFat: 0,
      saturatedFat: 0,
      transFat: 0,
      cholesterol: 0,
      sodium: 0,
      carbohydrates: 17,
      dietaryFiber: 0,
      sugars: 16,
      addedSugars: 0,
      vitamins: [],
      allergens: [],
      mayContain: [],
      ingredients: ['Miel de romero 100% pura'],
      preparationInstructions: 'Consumir directamente o endulzar infusiones.',
      storageInstructions: 'Conservar en lugar fresco y seco. Puede cristalizar de forma natural, lo que no altera sus propiedades.',
      isGlutenFree: true,
      isLactoseFree: true,
      isVegan: true,
      isVegetarian: true,
      isNutFree: true,
      isEggFree: true,
      isSoyFree: true,
    },
    certifications: [
      {
        id: 'cert-5',
        name: 'Producto Artesano',
        issuingBody: 'Junta de Comunidades de Castilla-La Mancha',
        certificateNumber: 'ART-2023-0789',
        issueDate: new Date('2023-05-20'),
        status: 'active',
        verified: true,
        category: 'quality',
      },
    ],
    productionInfo: {
      story: 'Nuestras abejas producen esta miel en las montañas de la Sierra de Alcaraz, donde el romero silvestre crece en abundancia. Mantenemos colmenas tradicionales y respetamos los ciclos naturales de las abejas.',
      farmName: 'Colmenas del Sur',
      origin: 'Sierra de Alcaraz, Albacete',
      productionMethod: 'Artesanal',
      harvestDate: new Date('2024-01-20'),
      productionDate: new Date('2024-01-25'),
      expiryDate: new Date('2026-01-25'),
      batchNumber: 'LOTE-024-0125',
      sustainabilityInfo: 'Apicultura sostenible y respetuosa con las abejas. Sin tratamientos agresivos.',
      animalWelfare: 'Colmenas respetadas y cuidadas. Extracción sin dañar a las abejas.',
      artisanProcess: 'Extracción en frío sin calentar para preservar todas las propiedades.',
      practices: ['biodiversity', 'zero_waste', 'local_sourcing'],
      producerName: 'Miguel Fernández',
      media: [],
    },
    attributes: [
      { 
        id: 'attr-10', 
        name: 'Floración', 
        value: 'Romero', 
        type: 'text', 
        visible: true,
        description: 'Tipo de flor predominante'
      },
      { 
        id: 'attr-11', 
        name: 'Textura', 
        value: 'Cremosa', 
        type: 'text', 
        visible: true,
        description: 'Consistencia de la miel'
      },
      { 
        id: 'attr-12', 
        name: 'Origen botánico', 
        value: 'Bosque mediterráneo', 
        type: 'text', 
        visible: true,
        description: 'Entorno de las colmenas'
      },
    ],
    status: 'active',
    visibility: 'public',
    publishedAt: new Date('2024-02-01'),
    sales: 78,
    revenue: 698.10,
    rating: 4.7,
    reviewCount: 15,
    views: 890,
    conversion: 8.8,
    createdAt: new Date('2024-02-01T09:15:00Z'),
    updatedAt: new Date('2024-02-20T10:30:00Z'),
    lastOrderDate: new Date('2024-03-10T12:20:00Z'),
  },
  {
    id: 'prod-004',
    producerId: 'user-123',
    name: 'Embutido Ibérico de Bellota',
    slug: 'embutido-iberico-de-bellota',
    shortDescription: 'Lomo embuchado de cerdo ibérico 100% bellota',
    fullDescription: 'Lomo de cerdo ibérico puro de bellota, curado de forma artesanal durante 4 meses. Procedente de cerdos criados en libertad en la dehesa extremeña y alimentados exclusivamente con bellotas durante la montanera.',
    categoryId: 'embutidos',
    categoryName: 'Embutidos',
    subcategoryId: 'lomo',
    tags: ['ibérico', 'bellota', 'artesano', 'dehesa'],
    mainImage: {
      id: 'img-007',
      url: '/images/products/lomo.jpg',
      alt: 'Lomo ibérico de bellota',
      caption: 'Lomo embuchado',
      isMain: true,
      sortOrder: 0,
    },
    gallery: [],
    basePrice: 32.50,
    comparePrice: 38.00,
    priceTiers: [
      { 
        id: 'tier6', 
        minQuantity: 2, 
        type: 'percentage', 
        value: 5, 
        label: '5% dto',
        savings: 3.25 
      },
    ],
    sku: 'EMB-IBE-001',
    barcode: '8434567890345',
    stock: 18,
    lowStockThreshold: 5,
    trackInventory: true,
    allowBackorders: false,
    weight: 0.8,
    weightUnit: 'kg',
    dimensions: { length: 30, width: 10, height: 10, unit: 'cm' },
    shippingClass: 'perishable',
    nutritionalInfo: {
      servingSize: '100g',
      servingSizeValue: 100,
      servingSizeUnit: 'g',
      calories: 380,
      protein: 35,
      totalFat: 26,
      saturatedFat: 9,
      transFat: 0,
      cholesterol: 85,
      sodium: 1100,
      carbohydrates: 0.5,
      dietaryFiber: 0,
      sugars: 0,
      addedSugars: 0,
      vitamins: [],
      allergens: [],
      mayContain: [],
      ingredients: [
        'Lomo de cerdo ibérico',
        'Sal marina',
        'Pimentón',
        'Ajo',
        'Orégano'
      ],
      preparationInstructions: 'Servir a temperatura ambiente, cortado en lonchas finas.',
      storageInstructions: 'Conservar en lugar fresco y seco. Una vez abierto, mantener refrigerado.',
      isGlutenFree: true,
      isLactoseFree: true,
      isVegan: false,
      isVegetarian: false,
      isNutFree: true,
      isEggFree: true,
      isSoyFree: true,
    },
    certifications: [
      {
        id: 'cert-6',
        name: 'Certificación Ibérico',
        issuingBody: 'ASICI',
        certificateNumber: 'IBE-2023-0567',
        issueDate: new Date('2023-02-10'),
        expiryDate: new Date('2024-02-10'),
        status: 'expired',
        verified: true,
        category: 'quality',
      },
    ],
    productionInfo: {
      story: 'Nuestros cerdos ibéricos pastan en libertad en la dehesa extremeña, alimentándose de bellotas durante la montanera. El proceso de curación se realiza de forma tradicional en secaderos naturales.',
      farmName: 'Dehesa Los Alcornoques',
      origin: 'Extremadura',
      productionMethod: 'Artesanal tradicional',
      harvestDate: new Date('2023-12-15'),
      productionDate: new Date('2023-12-20'),
      expiryDate: new Date('2024-08-20'),
      batchNumber: 'LOTE-023-1220',
      sustainabilityInfo: 'Dehesa en régimen de explotación sostenible',
      animalWelfare: 'Cría en libertad en la dehesa',
      artisanProcess: 'Curado natural en secaderos',
      practices: ['biodiversity', 'local_sourcing'],
      producerName: 'José Martín',
      media: [],
    },
    attributes: [
      { 
        id: 'attr-13', 
        name: 'Tipo de carne', 
        value: 'Cerdo ibérico puro', 
        type: 'text', 
        visible: true 
      },
      { 
        id: 'attr-14', 
        name: 'Curación', 
        value: 4, 
        type: 'number', 
        unit: 'meses',
        visible: true 
      },
      { 
        id: 'attr-15', 
        name: 'Alimentación', 
        value: 'Bellota', 
        type: 'text', 
        visible: true 
      },
    ],
    status: 'active',
    visibility: 'public',
    publishedAt: new Date('2024-01-20'),
    sales: 42,
    revenue: 1365.00,
    rating: 4.9,
    reviewCount: 12,
    views: 567,
    conversion: 7.4,
    createdAt: new Date('2024-01-15T11:20:00Z'),
    updatedAt: new Date('2024-02-18T09:15:00Z'),
    lastOrderDate: new Date('2024-03-12T14:30:00Z'),
  },
  {
    id: 'prod-005',
    producerId: 'user-123',
    name: 'Vino Tinto Crianza',
    slug: 'vino-tinto-crianza',
    shortDescription: 'Vino tinto crianza D.O. Ribera del Duero',
    fullDescription: 'Vino tinto crianza elaborado con uvas de la variedad Tempranillo. Crianza de 12 meses en barricas de roble francés y americano. De color cereza picota, aroma a frutos rojos y vainilla, con taninos sedosos.',
    categoryId: 'vinos',
    categoryName: 'Vinos',
    subcategoryId: 'tinto',
    tags: ['crianza', 'ribera', 'tempranillo'],
    mainImage: {
      id: 'img-008',
      url: '/images/products/vino.jpg',
      alt: 'Vino tinto crianza',
      caption: 'Crianza Ribera del Duero',
      isMain: true,
      sortOrder: 0,
    },
    gallery: [],
    basePrice: 14.95,
    comparePrice: 17.50,
    priceTiers: [
      { 
        id: 'tier7', 
        minQuantity: 6, 
        type: 'percentage', 
        value: 10, 
        label: '10% dto',
        savings: 8.97 
      },
    ],
    sku: 'VINO-001',
    barcode: '8434567890456',
    stock: 84,
    lowStockThreshold: 20,
    trackInventory: true,
    allowBackorders: true,
    weight: 1.5,
    weightUnit: 'kg',
    dimensions: { length: 8, width: 8, height: 30, unit: 'cm' },
    shippingClass: 'fragile',
    nutritionalInfo: {
      servingSize: '100ml',
      servingSizeValue: 100,
      servingSizeUnit: 'ml',
      calories: 85,
      protein: 0.1,
      totalFat: 0,
      saturatedFat: 0,
      transFat: 0,
      cholesterol: 0,
      sodium: 5,
      carbohydrates: 2.5,
      dietaryFiber: 0,
      sugars: 0.5,
      addedSugars: 0,
      vitamins: [],
      allergens: ['Sulfitos'],
      mayContain: [],
      ingredients: ['Uva Tempranillo', 'Sulfitos'],
      preparationInstructions: 'Servir a 16-18°C. Decantar antes de servir.',
      storageInstructions: 'Conservar en lugar fresco y oscuro, en posición horizontal.',
      isGlutenFree: true,
      isLactoseFree: true,
      isVegan: true,
      isVegetarian: true,
      isNutFree: true,
      isEggFree: true,
      isSoyFree: true,
    },
    certifications: [
      {
        id: 'cert-7',
        name: 'Denominación de Origen',
        issuingBody: 'Consejo Regulador Ribera del Duero',
        certificateNumber: 'DORIB-2023-089',
        issueDate: new Date('2023-01-15'),
        status: 'active',
        verified: true,
        category: 'origin',
      },
    ],
    productionInfo: {
      story: 'Nuestra bodega familiar elabora vinos en Ribera del Duero desde 1920. La tradición y el respeto por la uva son nuestra seña de identidad.',
      farmName: 'Bodegas El Páramo',
      origin: 'Ribera del Duero, Valladolid',
      productionMethod: 'Tradicional',
      harvestDate: new Date('2023-09-20'),
      productionDate: new Date('2023-10-15'),
      expiryDate: new Date('2028-10-15'),
      batchNumber: 'LOTE-023-1015',
      sustainabilityInfo: 'Viñedo ecológico en conversión',
      animalWelfare: 'No aplica',
      artisanProcess: 'Fermentación en depósitos de acero inoxidable',
      practices: ['local_sourcing'],
      producerName: 'Carlos Rodríguez',
      media: [],
    },
    attributes: [
      { 
        id: 'attr-16', 
        name: 'Variedad de uva', 
        value: 'Tempranillo', 
        type: 'text', 
        visible: true 
      },
      { 
        id: 'attr-17', 
        name: 'Añada', 
        value: 2020, 
        type: 'number', 
        unit: 'año',
        visible: true 
      },
      { 
        id: 'attr-18', 
        name: 'Crianza', 
        value: 'Crianza', 
        type: 'text', 
        visible: true 
      },
      { 
        id: 'attr-19', 
        name: 'Barrica', 
        value: '12 meses roble francés/americano', 
        type: 'text', 
        visible: true 
      },
      { 
        id: 'attr-20', 
        name: 'Graduación', 
        value: 14.5, 
        type: 'number', 
        unit: '% vol',
        visible: true 
      },
    ],
    status: 'active',
    visibility: 'public',
    publishedAt: new Date('2023-11-05'),
    sales: 124,
    revenue: 1853.80,
    rating: 4.6,
    reviewCount: 27,
    views: 1234,
    conversion: 10.0,
    createdAt: new Date('2023-11-01T16:30:00Z'),
    updatedAt: new Date('2024-01-25T12:45:00Z'),
    lastOrderDate: new Date('2024-03-13T11:20:00Z'),
  },
];

// ============================================================================
// ESTADÍSTICAS DE PRODUCTOS
// ============================================================================

export const MOCK_PRODUCT_STATS = {
  total: MOCK_PRODUCTS.length,
  active: MOCK_PRODUCTS.filter((p: Product) => p.status === 'active').length,
  lowStock: MOCK_PRODUCTS.filter(
    (p: Product) => p.lowStockThreshold && p.stock <= p.lowStockThreshold && p.stock > 0
  ).length,
  outOfStock: MOCK_PRODUCTS.filter((p: Product) => p.stock === 0).length,
  totalRevenue: MOCK_PRODUCTS.reduce((sum: number, p: Product) => sum + (p.revenue || 0), 0),
  totalSales: MOCK_PRODUCTS.reduce((sum: number, p: Product) => sum + (p.sales || 0), 0),
  totalViews: MOCK_PRODUCTS.reduce((sum: number, p: Product) => sum + (p.views || 0), 0),
  avgRating: parseFloat(
    (
      MOCK_PRODUCTS.filter((p: Product) => p.rating).reduce((sum: number, p: Product) => sum + (p.rating || 0), 0) /
      MOCK_PRODUCTS.filter((p: Product) => p.rating).length
    ).toFixed(1)
  ),
  byCategory: MOCK_PRODUCTS.reduce((acc, p) => {
    acc[p.categoryId] = (acc[p.categoryId] || 0) + 1;
    return acc;
  }, {} as Record<string, number>),
};

// ============================================================================
// CATEGORÍAS DE PRODUCTOS
// ============================================================================

export const PRODUCT_CATEGORIES = [
  { id: 'quesos', name: 'Quesos', icon: '🧀' },
  { id: 'aceites', name: 'Aceites', icon: '🫒' },
  { id: 'vinos', name: 'Vinos', icon: '🍷' },
  { id: 'embutidos', name: 'Embutidos', icon: '🥩' },
  { id: 'mieles', name: 'Mieles', icon: '🍯' },
  { id: 'conservas', name: 'Conservas', icon: '🥫' },
  { id: 'panaderia', name: 'Panadería', icon: '🍞' },
  { id: 'dulces', name: 'Dulces y Postres', icon: '🍰' },
  { id: 'bebidas', name: 'Bebidas', icon: '🥤' },
  { id: 'otros', name: 'Otros', icon: '📦' },
];

// ============================================================================
// SUBCATEGORÍAS POR CATEGORÍA
// ============================================================================

export const SUBCATEGORIES: Record<string, { id: string; name: string; description?: string }[]> = {
  quesos: [
    { id: 'curado', name: 'Curado', description: 'Quesos con más de 6 meses de curación' },
    { id: 'semicurado', name: 'Semicurado', description: 'Quesos con 2-6 meses de curación' },
    { id: 'fresco', name: 'Fresco', description: 'Quesos sin curar o con poco tiempo' },
    { id: 'azul', name: 'Azul', description: 'Quesos con moho penicillium' },
    { id: 'cabra', name: 'De cabra', description: 'Quesos elaborados con leche de cabra' },
    { id: 'oveja', name: 'De oveja', description: 'Quesos elaborados con leche de oveja' },
    { id: 'mezcla', name: 'Mezcla', description: 'Quesos elaborados con mezcla de leches' },
  ],
  aceites: [
    { id: 'virgen-extra', name: 'Virgen Extra', description: 'AOVE con acidez ≤ 0.8°' },
    { id: 'virgen', name: 'Virgen', description: 'Aceite de oliva virgen con acidez ≤ 2°' },
    { id: 'arbequina', name: 'Arbequina', description: 'Variedad de aceituna arbequina' },
    { id: 'picual', name: 'Picual', description: 'Variedad de aceituna picual' },
    { id: 'hojiblanca', name: 'Hojiblanca', description: 'Variedad de aceituna hojiblanca' },
    { id: 'cornicabra', name: 'Cornicabra', description: 'Variedad de aceituna cornicabra' },
  ],
  vinos: [
    { id: 'tinto', name: 'Tinto', description: 'Vino tinto' },
    { id: 'blanco', name: 'Blanco', description: 'Vino blanco' },
    { id: 'rosado', name: 'Rosado', description: 'Vino rosado' },
    { id: 'cava', name: 'Cava', description: 'Vino espumoso' },
    { id: 'dulce', name: 'Dulce', description: 'Vino dulce' },
    { id: 'crianza', name: 'Crianza', description: 'Vino con crianza' },
    { id: 'reserva', name: 'Reserva', description: 'Vino reserva' },
    { id: 'gran-reserva', name: 'Gran Reserva', description: 'Vino gran reserva' },
  ],
  embutidos: [
    { id: 'jamon', name: 'Jamón', description: 'Jamón curado' },
    { id: 'paleta', name: 'Paleta', description: 'Paleta curada' },
    { id: 'lomo', name: 'Lomo', description: 'Lomo embuchado' },
    { id: 'chorizo', name: 'Chorizo', description: 'Chorizo curado' },
    { id: 'salchichon', name: 'Salchichón', description: 'Salchichón curado' },
    { id: 'fuet', name: 'Fuet', description: 'Fuet catalán' },
  ],
  mieles: [
    { id: 'romero', name: 'Romero', description: 'Miel de romero' },
    { id: 'azahar', name: 'Azahar', description: 'Miel de azahar' },
    { id: 'tomillo', name: 'Tomillo', description: 'Miel de tomillo' },
    { id: 'espliego', name: 'Espliego', description: 'Miel de espliego' },
    { id: 'milflores', name: 'Milflores', description: 'Miel de múltiples flores' },
    { id: 'bosque', name: 'Bosque', description: 'Miel de bosque' },
  ],
  conservas: [
    { id: 'vegetales', name: 'Vegetales', description: 'Conservas de vegetales' },
    { id: 'pescados', name: 'Pescados', description: 'Conservas de pescado' },
    { id: 'mariscos', name: 'Mariscos', description: 'Conservas de marisco' },
    { id: 'patés', name: 'Patés', description: 'Patés y cremas' },
  ],
  panaderia: [
    { id: 'pan', name: 'Pan', description: 'Pan artesano' },
    { id: 'dulce', name: 'Dulce', description: 'Bollería dulce' },
    { id: 'salado', name: 'Salado', description: 'Bollería salada' },
  ],
  dulces: [
    { id: 'reposteria', name: 'Repostería', description: 'Dulces de repostería' },
    { id: 'chocolate', name: 'Chocolate', description: 'Productos de chocolate' },
    { id: 'conventual', name: 'Conventual', description: 'Dulces conventuales' },
  ],
  bebidas: [
    { id: 'zumos', name: 'Zumos', description: 'Zumos naturales' },
    { id: 'cerveza', name: 'Cerveza', description: 'Cerveza artesana' },
    { id: 'licores', name: 'Licores', description: 'Licores tradicionales' },
  ],
  otros: [
    { id: 'especias', name: 'Especias', description: 'Especias y condimentos' },
    { id: 'frutos-secos', name: 'Frutos secos', description: 'Frutos secos' },
    { id: 'deshidratados', name: 'Deshidratados', description: 'Productos deshidratados' },
  ],
};