/**
 * @file products_data.ts
 * @description Datos mock para productos
 */

import { type Product } from '@/types/product';

// ============================================================================
// PRODUCTOS DE EJEMPLO
// ============================================================================

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'prod-001',
    producerId: 'user-123',
    name: 'Queso Curado Artesanal 6 meses',
    slug: 'queso-curado-artesanal-6-meses',
    shortDescription: 'Queso de oveja curado durante 6 meses en cueva natural',
    fullDescription: 'Elaborado con leche cruda de oveja de nuestra propia ganadería en la Sierra de Grazalema. La leche se cuaja con cuajo natural de cordero y se prensa manualmente en moldes tradicionales de esparto. La maduración se realiza durante 12 meses en cuevas naturales, donde la humedad y temperatura constantes desarrollan su personalidad única.\n\nCaracterísticas:\n- Textura firme y ligeramente cristalizada\n- Sabor intenso y persistente con notas de frutos secos y hierbas de la sierra\n- Corteza natural lavada con aceite de oliva virgen extra\n\nReconocimientos:\n- Medalla de Oro en los World Cheese Awards 2024\n- Mejor Queso de España 2023 (Guía Gourmet)',
    categoryId: 'quesos',
    categoryName: 'Quesos',
    subcategoryId: 'curado',
    tags: ['artesano', 'ecológico', 'premiado', 'denominación origen', 'oveja', 'curado'],
    mainImage: {
      id: 'img-001',
      url: '/images/products/queso-curado.jpg',
      alt: 'Queso curado artesanal',
      isMain: true,
      sortOrder: 0,
    },
    gallery: [],
    basePrice: 24.50,
    comparePrice: 29.90,
    priceTiers: [
      { id: 'tier1', minQuantity: 2, type: 'percentage', value: 5, label: '5% dto' },
      { id: 'tier2', minQuantity: 5, type: 'percentage', value: 10, label: '10% dto' },
      { id: 'tier3', minQuantity: 10, type: 'percentage', value: 15, label: '15% dto' },
    ],
    sku: 'QUESO-CURADO-012',
    barcode: '8434567890123',
    stock: 45,
    lowStockThreshold: 10,
    trackInventory: true,
    allowBackorders: false,
    weight: 1.2,
    weightUnit: 'kg',
    dimensions: { length: 18, width: 18, height: 10, unit: 'cm' },
    shippingClass: 'perishable',
    nutritionalInfo: {
      servingSize: '100g',
      servingSizeValue: 100,
      servingSizeUnit: 'g',
      calories: 420,
      protein: 28,
      totalFat: 34,
      saturatedFat: 22,
      transFat: 0.5,
      cholesterol: 85,
      sodium: 620,
      carbohydrates: 1.5,
      dietaryFiber: 0,
      sugars: 0.2,
      addedSugars: 0,
      vitamins: [],
      allergens: ['Lácteos'],
      mayContain: ['Frutos de cáscara'],
      ingredients: [
        'Leche cruda de oveja (100% raza Manchega)',
        'Cuajo natural de cordero',
        'Sal marina',
        'Fermentos lácticos',
        'Cloruro cálcico'
      ],
      preparationInstructions: 'Servir a temperatura ambiente. Maridar con vinos tintos de la zona.',
      storageInstructions: 'Conservar en lugar fresco y seco. Una vez abierto, mantener refrigerado y consumir antes de 15 días.',
      isGlutenFree: true,
      isLactoseFree: false,
      isVegan: false,
      isVegetarian: true,
      isNutFree: false,
      isEggFree: true,
      isSoyFree: true,
    },
    certifications: [
      {
        id: 'cert-1',
        certificationId: 'dop',
        name: 'Denominación de Origen Protegida',
        issuingBody: 'Consejo Regulador D.O.',
        verified: true,
        expiryDate: new Date('2025-12-31'),
      },
      {
        id: 'cert-2',
        certificationId: 'eco',
        name: 'Agricultura Ecológica UE',
        issuingBody: 'Comité Andaluz de Agricultura Ecológica',
        verified: true,
        expiryDate: new Date('2024-11-30'),
      },
    ],
    productionInfo: {
      story: '"Nuestros quesos son el reflejo de nuestra tierra. Cada pieza cuenta la historia de nuestras ovejas, que pastan en libertad en las laderas de la sierra, alimentándose de tomillo y romero." - María García, Maesa Quesera.',
      origin: 'Sierra de Grazalema, Cádiz',
      farmName: 'Quesería El Gazpacho',
      producerName: 'María García',
      harvestDate: new Date('2024-02-15'),
      productionDate: new Date('2024-02-20'),
      expiryDate: new Date('2025-02-15'),
      batchNumber: 'LOTE-024-0224',
      productionMethod: 'Artesanal tradicional',
      sustainabilityInfo: 'Energía 100% renovable, reutilización de suero para alimentación animal, paneles solares, compostaje de residuos orgánicos.',
      animalWelfare: 'Cría en libertad, alimentación natural, pastoreo tradicional.',
      artisanProcess: 'Elaboración manual, prensado en moldes de esparto, maduración en cueva natural.',
      practices: ['renewable_energy', 'water_conservation', 'local_sourcing'],
      media: [
        {
          id: 'media-1',
          type: 'image',
          url: '/images/production/queseria.jpg',
          caption: 'Nuestra quesería',
        },
        {
          id: 'media-2',
          type: 'video',
          url: 'https://youtube.com/watch?v=...',
          thumbnail: '/images/production/video-thumb.jpg',
        },
      ],
    },
    attributes: [
      { id: 'attr-1', name: 'Tipo de leche', value: 'Oveja 100% Manchega', type: 'text', visible: true },
      { id: 'attr-2', name: 'Tiempo de curación', value: '12 meses', type: 'text', visible: true },
      { id: 'attr-3', name: 'Maduración', value: 'En cueva natural', type: 'text', visible: true },
      { id: 'attr-4', name: 'Textura', value: 'Firme y cristalizada', type: 'text', visible: true },
      { id: 'attr-5', name: 'Intensidad', value: 'Fuerte', type: 'text', visible: true },
    ],
    status: 'active',
    visibility: 'public',
    publishedAt: new Date('2024-01-15'),
    sales: 187,
    revenue: 5329.50,
    rating: 4.8,
    reviewCount: 42,
    views: 3452,
    conversion: 5.4,
    createdAt: new Date('2024-01-15T10:30:00Z'),
    updatedAt: new Date('2024-03-10T15:45:00Z'),
    lastOrderDate: new Date('2024-03-15T09:30:00Z'),
  },
  {
    id: 'prod-002',
    producerId: 'user-123',
    name: 'Aceite de Oliva Virgen Extra',
    slug: 'aceite-de-oliva-virgen-extra',
    shortDescription: 'AOVE cosecha temprana, variedad picual',
    fullDescription: 'Aceite de oliva virgen extra de cosecha temprana, elaborado con aceitunas de la variedad picual. Recogidas en el momento óptimo de maduración y prensadas en frío en las 24 horas siguientes a la cosecha.',
    categoryId: 'aceites',
    categoryName: 'Aceites',
    subcategoryId: 'virgen-extra',
    tags: ['ecológico', 'cosecha temprana', 'picual'],
    mainImage: {
      id: 'img-002',
      url: '/images/products/aceite.jpg',
      alt: 'Aceite de oliva virgen extra',
      isMain: true,
      sortOrder: 0,
    },
    gallery: [],
    basePrice: 16.90,
    comparePrice: 19.90,
    priceTiers: [
      { id: 'tier4', minQuantity: 3, type: 'percentage', value: 10, label: '10% dto' },
    ],
    sku: 'ACEITE-001',
    barcode: '8434567890234',
    stock: 62,
    lowStockThreshold: 15,
    trackInventory: true,
    allowBackorders: false,
    weight: 0.5,
    weightUnit: 'kg',
    dimensions: { length: 7, width: 7, height: 25, unit: 'cm' },
    shippingClass: 'standard',
    nutritionalInfo: {
      servingSize: '100ml',
      servingSizeValue: 100,
      servingSizeUnit: 'ml',
      calories: 884,
      totalFat: 100,
      saturatedFat: 14,
      transFat: 0,
      cholesterol: 0,
      sodium: 2,
      carbohydrates: 0,
      dietaryFiber: 0,
      sugars: 0,
      addedSugars: 0,
      protein: 0,
      vitamins: [],
      allergens: [],
      mayContain: [],
      ingredients: ['Aceitunas de la variedad Picual'],
      preparationInstructions: 'Ideal para consumir en crudo, en ensaladas o sobre pan tostado.',
      storageInstructions: 'Conservar en lugar fresco y seco, protegido de la luz.',
      isGlutenFree: true,
      isLactoseFree: true,
      isVegan: true,
      isVegetarian: true,
      isNutFree: true,
      isEggFree: true,
      isSoyFree: true,
    },
    certifications: [
      {
        id: 'cert-3',
        certificationId: 'eco',
        name: 'Agricultura Ecológica UE',
        issuingBody: 'Comité Andaluz de Agricultura Ecológica',
        verified: true,
        expiryDate: new Date('2024-10-31'),
      },
    ],
    productionInfo: {
      story: 'Nuestro aceite nace de olivos centenarios en la provincia de Jaén. La tradición familiar de más de 50 años nos ha enseñado a respetar los tiempos de la naturaleza.',
      origin: 'Jaén, Andalucía',
      farmName: 'Olivar El Abuelo',
      producerName: 'Antonio Sánchez',
      harvestDate: new Date('2023-11-05'),
      productionDate: new Date('2023-11-10'),
      expiryDate: new Date('2025-11-10'),
      batchNumber: 'LOTE-023-1123',
      productionMethod: 'Extracción en frío',
      sustainabilityInfo: 'Agricultura ecológica certificada',
      animalWelfare: 'Respeto al medio ambiente y biodiversidad',
      artisanProcess: 'Recolección manual y prensado en frío en 24 horas',
      practices: ['renewable_energy', 'local_sourcing'],
      media: [],
    },
    attributes: [
      { id: 'attr-6', name: 'Variedad', value: 'Picual', type: 'text', visible: true },
      { id: 'attr-7', name: 'Acidez', value: 0.2, type: 'number', unit: '°', visible: true },
      { id: 'attr-8', name: 'Cosecha', value: 'Temprana', type: 'text', visible: true },
    ],
    status: 'active',
    visibility: 'public',
    publishedAt: new Date('2023-11-15'),
    sales: 156,
    revenue: 2636.40,
    rating: 4.9,
    reviewCount: 38,
    views: 1890,
    conversion: 8.3,
    createdAt: new Date('2023-11-10T14:20:00Z'),
    updatedAt: new Date('2024-02-15T11:30:00Z'),
    lastOrderDate: new Date('2024-03-14T16:45:00Z'),
  },
  {
    id: 'prod-003',
    producerId: 'user-123',
    name: 'Miel de Romero Artesanal',
    slug: 'miel-de-romero-artesanal',
    shortDescription: 'Miel monofloral de romero',
    fullDescription: 'Miel de romero pura, recolectada en las colmenas situadas en las montañas de la Sierra de Alcaraz. De color ámbar claro y aroma intenso a romero.',
    categoryId: 'mieles',
    categoryName: 'Mieles',
    subcategoryId: undefined,
    tags: ['artesano', 'monofloral'],
    mainImage: {
      id: 'img-003',
      url: '/images/products/miel.jpg',
      alt: 'Miel de romero',
      isMain: true,
      sortOrder: 0,
    },
    gallery: [],
    basePrice: 8.95,
    comparePrice: undefined,
    priceTiers: [],
    sku: 'MIEL-001',
    barcode: undefined,
    stock: 23,
    lowStockThreshold: 6,
    trackInventory: true,
    allowBackorders: false,
    weight: 0.5,
    weightUnit: 'kg',
    dimensions: { length: 6, width: 6, height: 15, unit: 'cm' },
    shippingClass: 'standard',
    nutritionalInfo: {
      servingSize: '20g',
      servingSizeValue: 20,
      servingSizeUnit: 'g',
      calories: 64,
      totalFat: 0,
      saturatedFat: 0,
      transFat: 0,
      cholesterol: 0,
      sodium: 0,
      carbohydrates: 17,
      dietaryFiber: 0,
      sugars: 16,
      addedSugars: 0,
      protein: 0.1,
      vitamins: [],
      allergens: [],
      mayContain: [],
      ingredients: ['Miel de romero 100% pura'],
      preparationInstructions: 'Consumir directamente o endulzar infusiones.',
      storageInstructions: 'Conservar en lugar fresco y seco. Puede cristalizar de forma natural, lo que no altera sus propiedades.',
      isGlutenFree: true,
      isLactoseFree: true,
      isVegan: true,
      isVegetarian: true,
      isNutFree: true,
      isEggFree: true,
      isSoyFree: true,
    },
    certifications: [
      {
        id: 'cert-4',
        certificationId: 'artesano',
        name: 'Producto Artesano',
        issuingBody: 'Junta de Comunidades de Castilla-La Mancha',
        verified: true,
      },
    ],
    productionInfo: {
      story: 'Nuestras abejas producen esta miel en las montañas de la Sierra de Alcaraz, donde el romero silvestre crece en abundancia.',
      origin: 'Sierra de Alcaraz, Albacete',
      farmName: 'Colmenas del Sur',
      producerName: 'Miguel Fernández',
      harvestDate: new Date('2024-01-20'),
      productionDate: new Date('2024-01-25'),
      expiryDate: new Date('2026-01-25'),
      batchNumber: 'LOTE-024-0125',
      productionMethod: 'Artesanal',
      sustainabilityInfo: 'Apicultura sostenible y respetuosa con las abejas',
      animalWelfare: 'Colmenas respetadas y cuidadas',
      artisanProcess: 'Extracción en frío sin calentar',
      practices: ['biodiversity', 'zero_waste'],
      media: [],
    },
    attributes: [
      { id: 'attr-9', name: 'Floración', value: 'Romero', type: 'text', visible: true },
      { id: 'attr-10', name: 'Textura', value: 'Líquida', type: 'text', visible: true },
    ],
    status: 'active',
    visibility: 'public',
    publishedAt: new Date('2024-02-01'),
    sales: 78,
    revenue: 698.10,
    rating: 4.7,
    reviewCount: 15,
    views: 890,
    conversion: 8.8,
    createdAt: new Date('2024-02-01T09:15:00Z'),
    updatedAt: new Date('2024-02-20T10:30:00Z'),
    lastOrderDate: new Date('2024-03-10T12:20:00Z'),
  },
  // ... más productos (prod-004 a prod-009)
];

// ============================================================================
// ESTADÍSTICAS DE PRODUCTOS
// ============================================================================

export const MOCK_PRODUCT_STATS = {
  total: MOCK_PRODUCTS.length,
  active: MOCK_PRODUCTS.filter((p: Product) => p.status === 'active').length,
  lowStock: MOCK_PRODUCTS.filter(
    (p: Product) => p.lowStockThreshold && p.stock <= p.lowStockThreshold && p.stock > 0
  ).length,
  outOfStock: MOCK_PRODUCTS.filter((p: Product) => p.stock === 0).length,
  totalRevenue: MOCK_PRODUCTS.reduce((sum: number, p: Product) => sum + (p.revenue || 0), 0),
  totalSales: MOCK_PRODUCTS.reduce((sum: number, p: Product) => sum + (p.sales || 0), 0),
  totalViews: MOCK_PRODUCTS.reduce((sum: number, p: Product) => sum + (p.views || 0), 0),
  avgRating: parseFloat(
    (
      MOCK_PRODUCTS.filter((p: Product) => p.rating).reduce((sum: number, p: Product) => sum + (p.rating || 0), 0) /
      MOCK_PRODUCTS.filter((p: Product) => p.rating).length
    ).toFixed(1)
  ),
};

// ============================================================================
// CATEGORÍAS DE PRODUCTOS
// ============================================================================

export const PRODUCT_CATEGORIES = [
  { id: 'quesos', name: 'Quesos', icon: '🧀' },
  { id: 'aceites', name: 'Aceites', icon: '🫒' },
  { id: 'vinos', name: 'Vinos', icon: '🍷' },
  { id: 'embutidos', name: 'Embutidos', icon: '🥩' },
  { id: 'mieles', name: 'Mieles', icon: '🍯' },
  { id: 'conservas', name: 'Conservas', icon: '🥫' },
  { id: 'panaderia', name: 'Panadería', icon: '🍞' },
  { id: 'dulces', name: 'Dulces y Postres', icon: '🍰' },
  { id: 'bebidas', name: 'Bebidas', icon: '🥤' },
  { id: 'otros', name: 'Otros', icon: '📦' },
];

export const SUBCATEGORIES: Record<string, { id: string; name: string }[]> = {
  quesos: [
    { id: 'curado', name: 'Curado' },
    { id: 'semicurado', name: 'Semicurado' },
    { id: 'fresco', name: 'Fresco' },
    { id: 'azul', name: 'Azul' },
    { id: 'cabra', name: 'De cabra' },
    { id: 'oveja', name: 'De oveja' },
  ],
  aceites: [
    { id: 'virgen-extra', name: 'Virgen Extra' },
    { id: 'virgen', name: 'Virgen' },
    { id: 'arbequina', name: 'Arbequina' },
    { id: 'picual', name: 'Picual' },
    { id: 'hojiblanca', name: 'Hojiblanca' },
  ],
  vinos: [
    { id: 'tinto', name: 'Tinto' },
    { id: 'blanco', name: 'Blanco' },
    { id: 'rosado', name: 'Rosado' },
    { id: 'cava', name: 'Cava' },
    { id: 'dulce', name: 'Dulce' },
  ],
};